### ISSUE TITLE
No --skip-deleted-users?

### ISSUE THREAD

**Issue by jby** [ergon/migratemost#1]
Is there no --skip-deleted-users option?
since it bails on non-existing history for deleted users…

**Comment by jby** [comment]
I'd love to be able to provide you with a PR for a fix, but I'm not proficient enough in python... :(

**Comment by 7-plus-t** [comment]
Hi @jby 

What is your definition of a `--skip-deleted-users` option? Just so we are on the same page :)

The current implementation migrates all the users (because they are required by Mattermost to import their messages) and then generates a file with a list of the users that should be deactivated after the import is done (see https://github.com/ergon/migratemost/blob/master/HOWTO.md#deactivate-users-that-were-deleted-on-hipchat). 

Cheers,
Steven

**Comment by jby** [comment]
As said, the script fails due to missing history for a deleted user...
```
Traceback (most recent call last):
  File "/Users/jonasb/src/github/migratemost/migratemost.py", line 1147, in <module>
    main()
  File "/Users/jonasb/src/github/migratemost/migratemost.py", line 999, in main
    mm_direct_posts_of_user = migrate_direct_posts(mm_username_by_hc_id, mm_user)
  File "/Users/jonasb/src/github/migratemost/migratemost.py", line 525, in migrate_direct_posts
    hc_user_history = load_hipchat_user_history(hc_user_id)
  File "/Users/jonasb/src/github/migratemost/migratemost.py", line 449, in load_hipchat_user_history
    with open('%s/users/%d/history.json' % (migration_input_path, user_id), 'r') as hc_history_file:
IOError: [Errno 2] No such file or directory: '/Users/jonasb/Downloads/tmp/data/users/275/history.json'
```

**Comment by jby** [comment]
I'm just thinking that if I can exclude deleted users, I would avoid this problem. I don't know, maybe I can create an empty file where the script is looking for the history, haven't tried that...
Trying that now

**Comment by jby** [comment]
Then of course I'm faced with dealing with the utterly stupid way HipChat exports mention_names as usernames, which creates a complete mess when trying to import into an AD/LDAP enabled MM server where everyone that's created a different mention_name than their username will be unable to login (and maybe even to be imported)

**Comment by 7-plus-t** [comment]
Do these users have any messages in rooms that are migrated?

Your approach with creating empty history files could work. I guess the best solution would be to include the deleted users in the import because they could have messages in rooms, but ignore missing user history files?

**Comment by jby** [comment]
> I'm just thinking that if I can exclude deleted users, I would avoid this problem. I don't know, maybe I can create an empty file where the script is looking for the history, haven't tried that...
> Trying that now

Empty file gives different, probably expected, error:
```ValueError: No JSON object could be decoded```

**Comment by jby** [comment]
> Do these users have any messages in rooms that are migrated?
> 
> Your approach with creating empty history files could work. I guess the best solution would be to include the deleted users in the import because they could have messages in rooms, but ignore missing user history files?

And how would I ignore those?

**Comment by 7-plus-t** [comment]
> And how would I ignore those?

I would change the code accordingly

**Comment by jby** [comment]
I'm leaving work now, will look into this further tomorrow. Thanks for your help!

**Comment by 7-plus-t** [comment]
>  ... everyone that's created a different mention_name than their username will be unable to login 

Would it be a solution to provide a mapping between the Hipchat username and the LDAP login as input to the script, which would then replace the Hipchat usernames?

**Comment by 7-plus-t** [comment]
Just updated the code to ignore missing history files. Let me know if it works.

**Comment by jby** [comment]
> > ... everyone that's created a different mention_name than their username will be unable to login
> 
> Would it be a solution to provide a mapping between the Hipchat username and the LDAP login as input to the script, which would then replace the Hipchat usernames?

Well, Atlassian clearly states that they only care about email address in HipChat - so if it could match email addresses in LDAP and extract usernames from that and use instead of the stupid mention_names from HipChat, that would be great!

**Comment by jby** [comment]
> Just updated the code to ignore missing history files. Let me know if it works.

I'll try it out first thing tomorrow morning!

**Comment by jby** [comment]
Hmm, shouldn't leave an empty history.json in the dir for a deleted user, that still crashes with the same error as here: https://github.com/ergon/migratemost/issues/1#issuecomment-487599465

**Comment by jby** [comment]
So, your fix solves this problem. Found another, will create a new issue for it.
