### ISSUE TITLE
Partial old Hipchat exports vs. new rooms

### ISSUE THREAD

**Issue by anx-ag** [ergon/migratemost#14]
Hey again,

our hipchat source data was quite big and therefore the exporter of HipChat for whatever reason was unable to export all the history at once, so I had to split up the export in one file per year.
The problem with this is, that the users.json and rooms.json files contain the most recent information from today and migratemost is walking through them obviously and dies when it cannot find history for a room which is mentioned in the rooms.json file.

One tested workaround is to just create empty rooms in the hipchat export directory (see script below) and therefore faking empty rooms, but I guess it would make more sense to just ignore non existing rooms in the export or (not sure if that would work) check if the exported timerange (visible in metadata.json) is before the creation of the room and if that's the case, ignore it.

```
#!/bin/bash
# create up to 1000 empty rooms with empty history

cd /data/hipchat/export/rooms
for i in $(seq 1 1000); do
    test -d $i || mkdir $i && echo "[]" > $i/history.json
done
```

**Comment by 7-plus-t** [comment]
How is the export split? Does it contain only the rooms that had activity in that year and only the messages that date in that year?

If I understand correctly, I see the following options:

1. Write a script that joins the room exports before running Migratemost
2. As you suggested, improve Migratemost to not catastrophically fail when a room history file is missing, but rather log it and skip it. You could then run Migratemost several times (once per export) and import only the channel `*_posts.jsonl` and  `*_channels.jsonl` files repeatedly. This approach might have the drawback, that user-channel memberships are missing, unless you also import the users after every run. I'm not sure if the Mattermost bulk importer can handle that correctly though. 

If you would like to give 2. a go, I can change the script for you.

**Comment by anx-ag** [comment]
You can configure a timestamp range for the export and Hipchat does only export rooms and messages in rooms for this timeframe (also 1:1 messages are limited to this timeframe).

The layout of the (extracted) export looks like this:

metadata.json
users.json
rooms.json
users
  1/history.json
  2/history.json
  ...
  files
rooms
  1/history.json
  1/files
  2/history.json
  2/files
  ...

Since I've exported 2016, 2017, etc. in parts, I could tell that metadata.json differs (of course), but users.json and rooms.json is identical and that makes sense to some extent, since Hipchat is probably not really able to tell when a user joined or was active and when rooms were created (although this information definitely is in rooms.json).

So I guess while importing you're assuming that every room in rooms.json must exist and therefore migratemost fails when there's no history for a room mentioned in rooms.json.
It's pretty unlikely to get hipchat to fix this behaviour, so I would suggest to either a) ignore rooms where there's no history and skip over them or b) provide an additional command line flag to ignore them or c) only search for rooms created within start_date and end_data as mentioned in metadata.json or d) any other and probably better solution :)

Regarding the options you stated:
This is basically what I've done now. I learned that joining JSON files can be done with jq too, so f.ex.:

`jq -s add 2016/rooms/1/history.json 2017/rooms/1/history.json > overall/rooms/1/history.json`

should work (I haven't tried it though, my solution was uglier).
The attachments (files subfolders) are rsync'able, so they can be merged since all the IDs are unique, so basically one would have to rsync the source folders all together into a destination folder (excluding the history.json files) and then wrap something around the command above to make that work too. This has just been written out of my head (untested), will test it in the next few days though.

```
#!/bin/bash
 
SOURCEDIR="2016 2017"
TARGETDIR="overall"

# merge room and user structure as well as attachments
for sdir in $SOURCEDIR; do
  rsync --exclude "*.json" -av $sdir/ $TARGETDIR/
done

# copy user and room metadata information
cp $sdir/users.json $TARGETDIR
cp $sdir/rooms.json $TARGETDIR
  
# merge rooms and user history
for type in rooms users; do 
  for dir in $TARGETDIR/$type/*; do
    ID=$(basename $dir)
    SOURCEFILES=""
    for sdir in $SOURCEDIR; do
      needle=$sdir/$type/$ID/history.json
      test -f $needle && SOURCEFILES="$SOURCEFILES $needle"
    done
    jq -s add $SOURCEFILES > $TARGETDIR/$type/$ID/history.json
done
```

Regarding option 2: This also sounds interesting, not sure about the drawbacks, though. The user import (according to Mattermost) does not happen again. Mattermost bulk importer recognizes that the users are already there and just skips them (it seems to use creation date and other uniqueish metrics for identifying that).
My export (for whatever reason) contained a duplicate guest account and the Mattermost bulk importer tripped over that, so I had to manually delete the offending line and rerun the import and then the import went smooth again. The two lines looked identical in the input file though, so no idea how mattermost was able to distinguish them.

More to come here, just too little time now :-(

**Comment by anx-ag** [comment]
Alright, I had the pleasure to work on that again today and here's the version that's working and has been tested with 5 partial import directories today, just in case someone needs it


```
#!/bin/bash

# path to all the source directories (contents of the extracted hipchat tarballs)
# newest directory should be at the end
SOURCEDIR="/persistent/hipchat/2016 /persistent/hipchat/2017 /persistent/hipchat/2018 /persistent/hipchat/2019 /persistent/hipchat/2019-09"

# path to the destination directory that will hold all the merged data
TARGETDIR="/persistent/hipchat/overall"

LOG="$TARGETDIR/merge.log"

# create target directory if it does not exist
if ! test -d "$TARGETDIR"; then
       echo -n "Creating target directory $TARGETDIR..."
       if ! mkdir -p "$TARGETDIR"; then
               echo "failed."
               exit 1
       fi
       echo "done."
fi

# empty the logfile
echo "Merge started at $(date)" > $LOG

# merge room and user structure as well as attachments (but not the posts itself)
for sdir in $SOURCEDIR; do
  if ! test -d $sdir; then
    echo "sdir does not exist, exiting"
    exit 1
  fi
  echo -n "Syncing structure and attachments from $sdir to $TARGETDIR..."
  rsync --exclude /history.json -av $sdir/ $TARGETDIR/ >> $LOG 2>&1
  echo "done."
done

# copy user and room metadata from the most recent part (only the most recent information is relevant)
echo -n "Copying $sdir/users.json to $TARGETDIR..."
if ! cp -f $sdir/users.json $TARGETDIR; then
        echo "failed."
        exit 1
fi
echo "done."
echo -n "Copying $sdir/rooms.json to $TARGETDIR..."
if ! cp -f $sdir/rooms.json $TARGETDIR; then
        echo "failed."
        exit 1
fi
echo "done."

# merge rooms and user history
for type in rooms users; do
  for dir in $TARGETDIR/$type/*; do
    ID=$(basename $dir)
    SOURCEFILES=""
    for sdir in $SOURCEDIR; do
      needle=$sdir/$type/$ID/history.json
      test -f $needle && SOURCEFILES="$SOURCEFILES $needle"
    done
    if [ "$SOURCEFILES" != "" ]; then
      echo -n "Merge history ($type/$ID)..."
      if ! jq -s add $SOURCEFILES > $TARGETDIR/$type/$ID/history.json; then
            echo "failed."
      else
            echo "done."
      fi
    fi
  done
done

echo "Merge finished at $(date)" >> $LOG
```

**Comment by 7-plus-t** [comment]
Hi @anx-ag 

Would it be okay for you if I add the script to the Migratemost repository?

Thanks for all the contributions!

**Comment by anx-ag** [comment]
Sure, go ahead - that's why I posted it here :)

**Comment by 7-plus-t** [comment]
Added the script to master. Thanks for your contribution 🥇
