### ISSUE TITLE
Small delta imports cause errors because non existing history files

### ISSUE THREAD

**Issue by anx-ag** [ergon/migratemost#20]
I was cutting over today and did some very small incremental imports and one of them (the last one) did not contain any direct chats, but it did still contain group posts. migratemost threw the following error:

2019-09-23 06:29:40,446 - INFO - Concat all migration files into mm_all_data.jsonl
Traceback (most recent call last):
  File "migratemost/migratemost.py", line 1323, in <module>
    main()
  File "migratemost/migratemost.py", line 1253, in main
    concat_files(input_files, OUTPUT_ALL_IN_ONE_FILENAME)
  File "migratemost/migratemost.py", line 582, in concat_files
    with open(input_file_path, 'r') as input_file:
IOError: [Errno 2] No such file or directory: '/data/import/2019-09-23/mm_direct_channels.jsonl'
root@anx-i-mattermost0401:/persistent/opt/migratemost# vi /

I could fix that by creating an empty json file (only [] as content) at the location it complained about, but I think migratemost should do that automatically if there's not data to be found in the import.

**Comment by 7-plus-t** [comment]
The script now only warns about missing files when concatenating. Setting the content as empty would not work, as the bulk importer does not accept JSONL files without data (only version header).
