### ISSUE TITLE
Invalid Format String in timestamp_from_date

### ISSUE THREAD

**Issue by icelander** [ergon/migratemost#6]
Python Version: 2.7.8
OS: Windows 7

When running migratemost it fails on the first user with this error message:

![Screen Shot 2019-07-22 at 8 52 33 PM](https://user-images.githubusercontent.com/131287/61674695-ec52e800-acc2-11e9-845f-31c32ffc66dd.png)

The `%s` format is not supported on Windows machines. [This line](https://github.com/ergon/migratemost/blob/f720a87d651df9a5fb043223000ea0f91bb2f549/migratemost.py#L405) should be changed for cross-platform compatibility to:

```
return int(time.mktime(d.timetuple())) * 1000 + d.microsecond / 1000
```

**Comment by icelander** [comment]
Pull Request: #7

**Comment by 7-plus-t** [comment]
Thanks for the report and the fix! :)
